name: Build
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo run --release --verbose
